export const FORMULARIO_PROYECTO = 'FORMULARIO_PROYECTO';
export const AGREGAR_PROYECTO = 'AGREGAR_PROYECTO';
export const OBTENER_PROYECTOS = 'OBTENER_PROYECTOS';
export const PROYECTO_ERROR = 'PROYECTO_ERROR';
export const SELECCIONAR_PROYECTO = 'SELECCIONAR_PROYECTO';
export const MOSTRAR_EDITAR_PROYECTO = 'MOSTRAR_EDITAR_PROYECTO';
export const EDITAR_PROYECTO = 'EDITAR_PROYECTO';
export const ELIMINAR_PROYECTO = 'ELIMINAR_PROYECTO';

export const AGREGAR_TAREA = 'AGREGAR_TAREA';
export const TAREAS_PROYECTO = 'TAREAS_PROYECTO';
export const EDITAR_TAREA = 'EDITAR_TAREA';
export const ELIMINAR_TAREA = 'ELIMINAR_TAREA';

export const AGREGAR_USUARIO = 'AGREGAR_USUARIO';
export const ERROR_USUARIO = 'ERROR_USUARIO';
export const LOGIN_EXITOSO = 'LOGIN_EXITOSO';
export const REDIRECCIONAR = 'REDIRECCIONAR';
export const OBTENER_USUARIO = 'OBTENER_USUARIO';
export const ERROR_AUTENTICADO = 'ERROR_AUTENTICADO';
export const CERRAR_SESION = 'CERRAR_SESION';